name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: flutter build linux
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: flutter build windows
      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: flutter build macos
      - name: Build Android
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk
